"""
Application constants for the Fraud Analytics Platform.
"""

# Fraud Risk Levels
RISK_LEVEL_LOW = "LOW"
RISK_LEVEL_MEDIUM = "MEDIUM"
RISK_LEVEL_HIGH = "HIGH"
RISK_LEVEL_CRITICAL = "CRITICAL"

RISK_LEVELS = [RISK_LEVEL_LOW, RISK_LEVEL_MEDIUM, RISK_LEVEL_HIGH, RISK_LEVEL_CRITICAL]

# Fraud Score Thresholds
FRAUD_SCORE_THRESHOLD_LOW = 0.3
FRAUD_SCORE_THRESHOLD_MEDIUM = 0.6
FRAUD_SCORE_THRESHOLD_HIGH = 0.8

# Transaction Status
TRANSACTION_STATUS_PENDING = "PENDING"
TRANSACTION_STATUS_APPROVED = "APPROVED"
TRANSACTION_STATUS_REJECTED = "REJECTED"
TRANSACTION_STATUS_REVIEW = "REVIEW"

TRANSACTION_STATUSES = [
    TRANSACTION_STATUS_PENDING,
    TRANSACTION_STATUS_APPROVED,
    TRANSACTION_STATUS_REJECTED,
    TRANSACTION_STATUS_REVIEW,
]

# Alert Status
ALERT_STATUS_NEW = "NEW"
ALERT_STATUS_IN_PROGRESS = "IN_PROGRESS"
ALERT_STATUS_RESOLVED = "RESOLVED"
ALERT_STATUS_FALSE_POSITIVE = "FALSE_POSITIVE"

ALERT_STATUSES = [ALERT_STATUS_NEW, ALERT_STATUS_IN_PROGRESS, ALERT_STATUS_RESOLVED, ALERT_STATUS_FALSE_POSITIVE]

# Investigation Status
INVESTIGATION_STATUS_OPEN = "OPEN"
INVESTIGATION_STATUS_IN_PROGRESS = "IN_PROGRESS"
INVESTIGATION_STATUS_CLOSED = "CLOSED"

INVESTIGATION_STATUSES = [INVESTIGATION_STATUS_OPEN, INVESTIGATION_STATUS_IN_PROGRESS, INVESTIGATION_STATUS_CLOSED]

# API Response Codes
API_SUCCESS = 200
API_CREATED = 201
API_BAD_REQUEST = 400
API_UNAUTHORIZED = 401
API_FORBIDDEN = 403
API_NOT_FOUND = 404
API_INTERNAL_ERROR = 500

# Pagination
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 1000
DEFAULT_PAGE = 1

# Time Windows (in seconds)
TIME_WINDOW_5_MINUTES = 300
TIME_WINDOW_15_MINUTES = 900
TIME_WINDOW_1_HOUR = 3600
TIME_WINDOW_24_HOURS = 86400
