FROM apache/airflow:2.9.3-python3.11

USER airflow
WORKDIR /opt/airflow

COPY requirements.txt /tmp/fraud-platform-requirements.txt
RUN pip install --no-cache-dir -r /tmp/fraud-platform-requirements.txt

ENV PYTHONPATH=/opt/airflow/project
